theme: jekyll-theme-slate
github:
    repository_name: WheresMySound
    repository_url: http://github.com/barisione/WheresMySound
    owner_name: Marco Barisione
    owner_url: http://www.barisione.org/
title: Where’s My Sound
description: Free macOS app showing from which device sound comes from
#google_analytics: FIXME
navbar_pages:
    - url: /
      title: Home
